### ISSUE TITLE
There is no touchbar when running the example code

### ISSUE THREAD

**Issue by jeanbza** [loretoparisi/touchbar#1]
Am I missing something? When I run this code with xCode 8.1 + mac OS 10.12.1, I see no touchbar

**Comment by jeanbza** [comment]
edit: What do you mean by `macOS 10.12.1 SDK`? By this do you mean the operating system that I'm running xcode in?

**Comment by loretoparisi** [comment]
@jadekler Hi,
so basically if you from bash do

```
$ sw_vers  
ProductName:    Mac OS X
ProductVersion: 10.12.1
BuildVersion:   16B2657
```

you should have the `16B2657` installed.
To obtain this build of `10.12.1` you can update manually from: https://support.apple.com/kb/dl1897?locale=en_US

For some reasons, `macOS 10.12.1` has a previous build - that is the build number `16B2555`, that is also an update from the AppStore, that does not contain the TouchBar in Xcode, so in that case you have to update manually.

You can update Xcode to `Xcode Version 8.1 (8B62)` as normally you would do via the AppStore.

To enter the Apple forum's discussion about this issue - see here: https://forums.developer.apple.com/thread/66629

**Comment by jeanbza** [comment]
Thanks @loretoparisi
